### ISSUE TITLE
line 39 in scripts "to_run"

### ISSUE THREAD

**Issue by jingzhuio** [ARS-toscana/ConcePTIONAlgorithmPregnancies#13]
Line 39:
> source(paste0(thisdir,"/p_parameters_pregnancy/04_algorithms_pregnancy.R")) 
gives error messages:
Error in save(meaning_of_visit_pregnancy, file = paste0(direxp, "meaning_of_visit_pregnancy.RData")) : 
  object "meaning_of_visit_pregnancy" not found

**Comment by clobart** [comment]
Sorry we didn't receive the notification @jingzhuio

**Comment by jingzhuio** [comment]
No problems. the script kept running after that error message. Shall I do something now and rerun the script or ...? @clobart

**Comment by clobart** [comment]
I fixed the bug, it's a really small thing that doesn't affect your results (since you don't have pregnancy info in visit_occurrence)
Thank you very much to warn us.

I'll close this issue!
