### ISSUE TITLE
line 40 in script "to_run"

### ISSUE THREAD

**Issue by jingzhuio** [ARS-toscana/ConcePTIONAlgorithmPregnancies#14]
Line 40:
> source(paste0(thisdir,"/p_parameters_pregnancy/05_check_coding_system.R"))
gives error messages:

Error in eval(ei, envir) : 
  There is an error in coding system: one or more coding system in your data are not included in the list of coding systems supported by this script.Please contact the script programmer.

**Comment by clobart** [comment]
At this stage, you can ignore this error. 
It's a message displayed by us.
