### ISSUE TITLE
Have all parameters in one configuration file

### ISSUE THREAD

**Issue by DSThayer** [ARS-toscana/ConcePTIONAlgorithmPregnancies#15]
Suggestion: it would be a lot easier to use the algorithm if all parameters that a user must specify were in a single file (that contained nothing else) rather than interspersed with other code throughout a number of different files. 

I think it would be easier to support new users of the algorithm if this were the case, and it would be a lot easier to download and run an updated version of the code.

**Comment by clobart** [comment]
Thanks for the suggestion! We'll take into account for next programs.

We put together all the parameters for transparency, surely it's less easy to fill in for DAPs, but it's useful for the program.
