### ISSUE TITLE
Join issue in step_03_04_T2.2_internal_consistency_for_EUROCAT

### ISSUE THREAD

**Issue by DSThayer** [ARS-toscana/ConcePTIONAlgorithmPregnancies#17]
person_id in EUROCAT is numeric, while it's a character field in other data sources. This causes a join error in the mentioned file.

I have solved this by using `as.integer` to convert `D3_persons.person_id` and `output_spells_category$person_id` to integers (inserted at line 52 of the file). I'm not sure that is the right solution, but it makes the code work for me.

**Comment by GiorgioLimoncella** [comment]
Thanks for fixing the bug! As person_ids are usually characters, I would prefer to turn EUROCAT ids into characters rather than the other way around, how does that sound?
(because maybe some future DAP will have EUROCAT ids as character and converting them to integer will create problems)

**Comment by DSThayer** [comment]
That's fine. Let me know when a corrected version is available, and I'll
test it.

**Comment by GiorgioLimoncella** [comment]
The bug has been fixed, thank you!
