### ISSUE TITLE
Questions for the result of the pregnancy algorithm

### ISSUE THREAD

**Issue by jingzhuio** [ARS-toscana/ConcePTIONAlgorithmPregnancies#18]
From D3_pregnancy_final.RData file there are 53421 observations with 43119 IDs with pregnancy_end_date range from 2018-01-01 to 2020-08-12
How are these observation chosen? from the raw data we have 55000-60000 observations each year.
We have 2021 too.

Are SB, SA, T etc. identified by diagnose code from EVENTS table or gestational length or both? Termination seem to be quite a lot. Could you please tell me how the algorithm selected these observations? @clobart

**Comment by jingzhuio** [comment]
where can I get the SAP of the pregnancy algorithm please? @clobart

**Comment by clobart** [comment]
> where can I get the SAP of the pregnancy algorithm please? @clobart

This is the link of the SAP
https://docs.google.com/document/d/1HzmoAOi9x9CSRZdg5qCwEHTQqMvJSthZ/

**Comment by jingzhuio** [comment]
I was trying to extract T (from D3_pregnancy_final, 15902 obs with 14001 unique IDs) by using the ICD10 diagnose code in  .../p_parameters_pregnancy /03_conceptsets/concept_set_codes_pgegnancy_2220601_format_VAC4EU and noticed that after filtering  "ICD10" and "TOPFA", there is F89 which is "Unspecified disorder of psychological development". 
Aslo the folder do not contain 03_conceptsets_UOSL. Would these matter to the counting?

**Comment by GiorgioLimoncella** [comment]
> I was trying to extract T (from D3_pregnancy_final, 15902 obs with 14001 unique IDs) by using the ICD10 diagnose code in .../p_parameters_pregnancy /03_conceptsets/concept_set_codes_pgegnancy_2220601_format_VAC4EU and noticed that after filtering "ICD10" and "TOPFA", there is F89 which is "Unspecified disorder of psychological development". Aslo the folder do not contain 03_conceptsets_UOSL. Would these matter to the counting?


**To extract termination** from D3_pregnancy_final please select those having type_of_pregnancy_end == "T". The codes in concept_set_codes_pgegnancy_2220601_format_VAC4EU are an old list and are no longer used, the diagnostic codelist is **ALL_full_codelist_pregnancy.csv**. Sorry for the confusion, we will dischard the old codelist. 
Regarding **03_conceptsets_UOSL**: the file does not exist because Oslo did not notify procedure code to be extracted.

**Comment by GiorgioLimoncella** [comment]
> From D3_pregnancy_final.RData file there are 53421 observations with 43119 IDs with pregnancy_end_date range from 2018-01-01 to 2020-08-12 How are these observation chosen? from the raw data we have 55000-60000 observations each year. We have 2021 too.

What is the recommended_end_date in the CDM_SOURCE file? 
Please note that D3_pregnancy_final has one record per pregnancy
How many pregnancies do we expect per year?

**Comment by jingzhuio** [comment]
recommended_end_date in the CDM_SOURCE is 20211231
from the birth registry, we expect 55000-60000 pregnancies per year.
I checked for T and SB, the numbers were not the same as what I get from D3 but not too far off. I guess they are from EVENTS table.

**Comment by jingzhuio** [comment]
I will check again with the right codelist and let you know. 
From EVENT table we have only one date. I will use end_of_pregnancy in D3 to match the date in EVENTS table as the outcomes happens at the end of pregnancy.

**Comment by GiorgioLimoncella** [comment]
Some tools are implemented in the script which may be useful in this case:

- in the final report (g_describe_html/HTML_pregnancy_description.html) there are some descriptive analyses indicating the provenance of the pregnancies 

- for each stream an intermediate dataset is saved in the g_intemediate folder, e.g. all records from MBRN are saved in D3_stream_PROMPT, and the records remaining after the exclusions for internal consistency are saved in D3_strem_PROMPT_check. 
(records from EVENT are saved in D3_stream_CONCEPTSETS and D3_stream_CONCEPTSETS_check)

- the main intermediate datasets are described in html files that you can find in the g_describe_html folder (D3_stream_PROMPT is in g_describe_html/02 )

If there are any doubts, we can schedule a call and check together if the parameter entry is correct, you can contact me at giorgio.limoncella@ars.toscana.it

**Comment by jingzhuio** [comment]
@GiorgioLimoncella 
Hi Giorgio,
The email delivery to you has failed so I copied as below:

Many thanks for your explanation! I had another look this morning and it looks like what we suspected - no observations from MBRN are included, as D3_stream_PROMT_check has 0 rows. 
I noticed that there are 3 big criteria, time range, fertile age, date in spell? I wouldn't believe PROMPT_check should be 0 though. 

It'd be a good idea to have a quick call. I'm all free this afternoon and then I'll be on holiday til 3rd August. If you are available when I'm away, my colleague Luigi Maglanoc will take over and I will let him know today.

**Comment by GiorgioLimoncella** [comment]
sorry for the inconvenience! I am available this afternoon, for the moment we can get in touch via giorgio.limoncella@unifi.it.

**Comment by jingzhuio** [comment]
@GiorgioLimoncella @clobart 
Hi Giorgio and Claudia,
I made some misakes with the SURVEY tables before I went on holiday and we have to rerun the pregnancy algorithm. Somehow the  CONCEPTSET only include observations from 2019 when it supposed to include from 2010. Could you help us have a look? Luigi has sent an email to you both this morning.
