### ISSUE TITLE
Issue with step_07_01_create_aggregated_tables.r

### ISSUE THREAD

**Issue by DSThayer** [ARS-toscana/ConcePTIONAlgorithmPregnancies#19]
When creating aggregated tables, there is a pregnancy end type of "LB/SB" in list_of_type.

When trying to write the output CSV file, this type fails, because the / is interpreted as a subdirectory in the fwrite command.

**Comment by DSThayer** [comment]
The issue also exists in step 07 04. 

I have added a kludge of altering those file names to make it work for now.

**Comment by GiorgioLimoncella** [comment]
thanks @DSThayer, I turned "LB/SB" in "LB_or_SB", it should no longer create errors
