### ISSUE TITLE
Error in check_coding_system

### ISSUE THREAD

**Issue by DanOV** [ARS-toscana/ConcePTIONAlgorithmPregnancies#20]
Error during evaluation of coding system.

It says that SIDIAP_coding is missing:

<pre style="color:#000000;background:#ffffff;"><span style="color:#44aadd; ">&gt;</span> source<span style="color:#808030; ">(</span>paste0<span style="color:#808030; ">(</span>thisdir<span style="color:#808030; ">,</span><span style="color:#0000e6; ">"/p_parameters_pregnancy/05_check_coding_system.R"</span><span style="color:#808030; ">)</span><span style="color:#808030; ">)</span>
Missing coding system are<span style="color:#808030; ">:</span>
 SIDIAP_coding 
Error <span style="color:#800000; font-weight:bold; ">in</span> <span style="color:#400000; ">eval</span><span style="color:#808030; ">(</span>ei<span style="color:#808030; ">,</span> envir<span style="color:#808030; ">)</span> <span style="color:#808030; ">:</span> 
  There <span style="color:#800000; font-weight:bold; ">is</span> an error <span style="color:#800000; font-weight:bold; ">in</span> coding system<span style="color:#808030; ">:</span> one <span style="color:#800000; font-weight:bold; ">or</span> more coding system <span style="color:#800000; font-weight:bold; ">in</span> your data are <span style="color:#800000; font-weight:bold; ">not</span> included <span style="color:#800000; font-weight:bold; ">in</span> the <span style="color:#400000; ">list</span> of coding systems supported by this script<span style="color:#808030; ">.</span>Please contact the script programmer<span style="color:#808030; ">.</span>
</pre>

**Comment by clobart** [comment]
No, this is more a "warning" message that we displayed.
We will delete it, just ignore it! Thanks :)
