### ISSUE TITLE
Warnings in Step 04 and Issue in Main Reconciliation

### ISSUE THREAD

**Issue by DanOV** [ARS-toscana/ConcePTIONAlgorithmPregnancies#21]
Several warnings during Step04:

<pre style="color:#000000;background:#ffffff;">source<span style="color:#808030; ">(</span>paste0<span style="color:#808030; ">(</span>thisdir<span style="color:#808030; ">,</span><span style="color:#0000e6; ">"/p_steps_pregnancy/step_03_01_T2.2_internal_consistency_for_prompts.R"</span><span style="color:#808030; ">)</span><span style="color:#808030; ">)</span> 
Describing D3_Stream_PROMPTS_check 
<span style="color:#808030; ">[</span><span style="color:#008c00; ">1</span><span style="color:#808030; ">]</span> <span style="color:#0000e6; ">"Internal consistency for PROMPTS checked"</span>
<span style="color:#074726; ">Warning</span> message<span style="color:#808030; ">:</span>
<span style="color:#800000; font-weight:bold; ">In</span> <span style="color:#400000; ">max</span><span style="color:#808030; ">(</span>num_spell<span style="color:#808030; ">)</span> <span style="color:#808030; ">:</span> no non<span style="color:#44aadd; ">-</span>missing arguments to <span style="color:#400000; ">max</span><span style="color:#808030; ">;</span> returning <span style="color:#44aadd; ">-</span>Inf
source<span style="color:#808030; ">(</span>paste0<span style="color:#808030; ">(</span>thisdir<span style="color:#808030; ">,</span><span style="color:#0000e6; ">"/p_steps_pregnancy/step_03_02_T2.2_internal_consistency_for_conceptsets.R"</span><span style="color:#808030; ">)</span><span style="color:#808030; ">)</span> 
Describing D3_Stream_CONCEPTSETS_check 
<span style="color:#808030; ">[</span><span style="color:#008c00; ">1</span><span style="color:#808030; ">]</span> <span style="color:#0000e6; ">"Internal consistency for CONCEPTSETS checked"</span>
<span style="color:#074726; ">Warning</span> message<span style="color:#808030; ">:</span>
<span style="color:#800000; font-weight:bold; ">In</span> <span style="color:#400000; ">max</span><span style="color:#808030; ">(</span>num_spell<span style="color:#808030; ">)</span> <span style="color:#808030; ">:</span> no non<span style="color:#44aadd; ">-</span>missing arguments to <span style="color:#400000; ">max</span><span style="color:#808030; ">;</span> returning <span style="color:#44aadd; ">-</span>Inf
source<span style="color:#808030; ">(</span>paste0<span style="color:#808030; ">(</span>thisdir<span style="color:#808030; ">,</span><span style="color:#0000e6; ">"/p_steps_pregnancy/step_04_03_T2.3_first_part_reconciliation.R"</span><span style="color:#808030; ">)</span><span style="color:#808030; ">)</span>
<span style="color:#808030; ">[</span><span style="color:#008c00; ">1</span><span style="color:#808030; ">]</span> <span style="color:#0000e6; ">"Start recoinciliation in group - GREEN"</span>
<span style="color:#808030; ">[</span><span style="color:#008c00; ">1</span><span style="color:#808030; ">]</span> <span style="color:#0000e6; ">"Start recoinciliation in group - YELLOW"</span>
<span style="color:#808030; ">[</span><span style="color:#008c00; ">1</span><span style="color:#808030; ">]</span> <span style="color:#0000e6; ">"Start recoinciliation in group - BLUE"</span>
<span style="color:#808030; ">[</span><span style="color:#008c00; ">1</span><span style="color:#808030; ">]</span> <span style="color:#0000e6; ">"Start recoinciliation in group - RED"</span>
<span style="color:#808030; ">[</span><span style="color:#008c00; ">1</span><span style="color:#808030; ">]</span> <span style="color:#0000e6; ">"Save D3_groups_of_pregnancies"</span>
Describing D3_groups_of_pregnancies 
<span style="color:#074726; ">Warning</span> messages<span style="color:#808030; ">:</span>
<span style="color:#008c00; ">1</span><span style="color:#808030; ">:</span> <span style="color:#800000; font-weight:bold; ">In</span> <span style="color:#400000; ">max</span><span style="color:#808030; ">(</span>n_rep<span style="color:#808030; ">)</span> <span style="color:#808030; ">:</span> no non<span style="color:#44aadd; ">-</span>missing arguments to <span style="color:#400000; ">max</span><span style="color:#808030; ">;</span> returning <span style="color:#44aadd; ">-</span>Inf
<span style="color:#008c00; ">2</span><span style="color:#808030; ">:</span> <span style="color:#800000; font-weight:bold; ">In</span> <span style="color:#400000; ">max</span><span style="color:#808030; ">(</span>n_rep<span style="color:#808030; ">)</span> <span style="color:#808030; ">:</span> no non<span style="color:#44aadd; ">-</span>missing arguments to <span style="color:#400000; ">max</span><span style="color:#808030; ">;</span> returning <span style="color:#44aadd; ">-</span>Inf
<span style="color:#008c00; ">3</span><span style="color:#808030; ">:</span> <span style="color:#800000; font-weight:bold; ">In</span> <span style="color:#400000; ">min</span><span style="color:#808030; ">.</span>default<span style="color:#808030; ">(</span>numeric<span style="color:#808030; ">(</span><span style="color:#008c00; ">0</span><span style="color:#808030; ">)</span><span style="color:#808030; ">,</span> na<span style="color:#808030; ">.</span>rm <span style="color:#808030; ">=</span> <span style="color:#074726; ">TRUE</span><span style="color:#808030; ">)</span> <span style="color:#808030; ">:</span>
  no non<span style="color:#44aadd; ">-</span>missing arguments to <span style="color:#400000; ">min</span><span style="color:#808030; ">;</span> returning Inf
<span style="color:#008c00; ">4</span><span style="color:#808030; ">:</span> <span style="color:#800000; font-weight:bold; ">In</span> <span style="color:#400000; ">max</span><span style="color:#808030; ">.</span>default<span style="color:#808030; ">(</span>numeric<span style="color:#808030; ">(</span><span style="color:#008c00; ">0</span><span style="color:#808030; ">)</span><span style="color:#808030; ">,</span> na<span style="color:#808030; ">.</span>rm <span style="color:#808030; ">=</span> <span style="color:#074726; ">TRUE</span><span style="color:#808030; ">)</span> <span style="color:#808030; ">:</span>
  no non<span style="color:#44aadd; ">-</span>missing arguments to <span style="color:#400000; ">max</span><span style="color:#808030; ">;</span> returning <span style="color:#44aadd; ">-</span>Inf
<span style="color:#008c00; ">5</span><span style="color:#808030; ">:</span> <span style="color:#800000; font-weight:bold; ">In</span> <span style="color:#400000; ">max</span><span style="color:#808030; ">(</span>n_rep<span style="color:#808030; ">)</span> <span style="color:#808030; ">:</span> no non<span style="color:#44aadd; ">-</span>missing arguments to <span style="color:#400000; ">max</span><span style="color:#808030; ">;</span> returning <span style="color:#44aadd; ">-</span>Inf
<span style="color:#008c00; ">6</span><span style="color:#808030; ">:</span> <span style="color:#800000; font-weight:bold; ">In</span> <span style="color:#400000; ">max</span><span style="color:#808030; ">(</span>n_rep<span style="color:#808030; ">)</span> <span style="color:#808030; ">:</span> no non<span style="color:#44aadd; ">-</span>missing arguments to <span style="color:#400000; ">max</span><span style="color:#808030; ">;</span> returning <span style="color:#44aadd; ">-</span>Inf
<span style="color:#008c00; ">7</span><span style="color:#808030; ">:</span> <span style="color:#800000; font-weight:bold; ">In</span> <span style="color:#400000; ">min</span><span style="color:#808030; ">.</span>default<span style="color:#808030; ">(</span>numeric<span style="color:#808030; ">(</span><span style="color:#008c00; ">0</span><span style="color:#808030; ">)</span><span style="color:#808030; ">,</span> na<span style="color:#808030; ">.</span>rm <span style="color:#808030; ">=</span> <span style="color:#074726; ">TRUE</span><span style="color:#808030; ">)</span> <span style="color:#808030; ">:</span>
  no non<span style="color:#44aadd; ">-</span>missing arguments to <span style="color:#400000; ">min</span><span style="color:#808030; ">;</span> returning Inf
<span style="color:#008c00; ">8</span><span style="color:#808030; ">:</span> <span style="color:#800000; font-weight:bold; ">In</span> <span style="color:#400000; ">max</span><span style="color:#808030; ">.</span>default<span style="color:#808030; ">(</span>numeric<span style="color:#808030; ">(</span><span style="color:#008c00; ">0</span><span style="color:#808030; ">)</span><span style="color:#808030; ">,</span> na<span style="color:#808030; ">.</span>rm <span style="color:#808030; ">=</span> <span style="color:#074726; ">TRUE</span><span style="color:#808030; ">)</span> <span style="color:#808030; ">:</span>
  no non<span style="color:#44aadd; ">-</span>missing arguments to <span style="color:#400000; ">max</span><span style="color:#808030; ">;</span> returning <span style="color:#44aadd; ">-</span>Inf
<span style="color:#008c00; ">9</span><span style="color:#808030; ">:</span> <span style="color:#800000; font-weight:bold; ">In</span> <span style="color:#400000; ">min</span><span style="color:#808030; ">.</span>default<span style="color:#808030; ">(</span>numeric<span style="color:#808030; ">(</span><span style="color:#008c00; ">0</span><span style="color:#808030; ">)</span><span style="color:#808030; ">,</span> na<span style="color:#808030; ">.</span>rm <span style="color:#808030; ">=</span> <span style="color:#074726; ">TRUE</span><span style="color:#808030; ">)</span> <span style="color:#808030; ">:</span>
  no non<span style="color:#44aadd; ">-</span>missing arguments to <span style="color:#400000; ">min</span><span style="color:#808030; ">;</span> returning Inf
<span style="color:#008c00; ">10</span><span style="color:#808030; ">:</span> <span style="color:#800000; font-weight:bold; ">In</span> <span style="color:#400000; ">max</span><span style="color:#808030; ">.</span>default<span style="color:#808030; ">(</span>numeric<span style="color:#808030; ">(</span><span style="color:#008c00; ">0</span><span style="color:#808030; ">)</span><span style="color:#808030; ">,</span> na<span style="color:#808030; ">.</span>rm <span style="color:#808030; ">=</span> <span style="color:#074726; ">TRUE</span><span style="color:#808030; ">)</span> <span style="color:#808030; ">:</span>
  no non<span style="color:#44aadd; ">-</span>missing arguments to <span style="color:#400000; ">max</span><span style="color:#808030; ">;</span> returning <span style="color:#44aadd; ">-</span>Inf
</pre>

After step04, the process cannot continue due to the following error in 05 MAIN RECONCILIATION
> source(paste0(thisdir,"/p_steps_pregnancy/step_05_01_T2.2_reconciliation.R"))
Error in eval(bysub, x, parent.frame()) : 
  object 'pers_group_id' not found
In addition: Warning message:
In max(n) : no non-missing arguments to max; returning -Inf

**Comment by GiorgioLimoncella** [comment]
Probably the error comes from a previous step, can we arrange a call to check the results of the intermediate steps together? 
please contact me at giorgio.limoncella@ars.toscana.it

**Comment by DanOV** [comment]
Hi,
I think that the issue was solved by fixing the INSTANCE table by following you indications.
Thanks a lot for the help.
