### ISSUE TITLE
Unclear how to complete validation variables

### ISSUE THREAD

**Issue by DSThayer** [ARS-toscana/ConcePTIONAlgorithmPregnancies#24]
A couple of things that are not clear from the validation documentation:

1. Which date should be used for reference for values such as pregnancy_start_date_difference?

e.g. "1 = < 5 days before". Does this mean the correct pregnancy start date is <5 days before the algorithm's pregnancy start date, or is it the other way around?

2. How to complete the variables if I conclude that a pregnancy should not be captured as a pregnancy at all? I can set pregnancy_start_date_correct='N' etc. but there isn't an applicable value for the _difference variables.

**Comment by GiorgioLimoncella** [comment]
sorry the instructions are not clear! I will try to update them. 



1. "1 = < 5 days before" mean the correct pregnancy start date is <5 days before the algorithm's pregnancy start date.

2.  if a record should not represent a pregnancy it is very important that you write the reason in the comments section (for possible algorithm update), then you can fill in the columns "pregnancy_start_date_correct", "pregnancy_end_date_correct" , "type_of_pregnancy_end_correct" with the value "N", and leave the other columns empty

**Comment by DSThayer** [comment]
Thanks very much for clarifying!
