### ISSUE TITLE
Pregnancies created based on nonspecific code

### ISSUE THREAD

**Issue by DSThayer** [ARS-toscana/ConcePTIONAlgorithmPregnancies#26]
In our validation sample, we had several pregnancies created based solely on the code R15X (fecal incontinence), with no other evidence of a pregnancy.

This does not seem correct, since this condition (while common during delivery) is not specific to pregnancy.

**Comment by clobart** [comment]
@acidroyo-UMCU @msturkenboom @cduransalinas

**Comment by DuranSalinas** [comment]
Totally agree.
I will check it.
Could you please let me know the concept set where this code is?

**Comment by clobart** [comment]
It's in both _Livebirth_ and _BirthPossible_
> Totally agree. I will check it. Could you please let me know the concept set where this code is?
