### ISSUE TITLE
HSD error- thisdir,"/p_parameters_pregnancy/05_check_coding_system.R 

### ISSUE THREAD

**Issue by elisabianchini** [ARS-toscana/ConcePTIONAlgorithmPregnancies#28]
> source(paste0(thisdir,"/p_parameters_pregnancy/05_check_coding_system.R"))
Error in eval(ei, envir) : 
  There is an error in coding system: one or more coding system in your data are not included in the list of coding systems supported by this script.Please contact the script programmer.

**Comment by clobart** [comment]
You can skip this, anyway we removed this message that can be misleading!
