### ISSUE TITLE
definition of "Termination" and "Unknown"

### ISSUE THREAD

**Issue by jingzhuio** [ARS-toscana/ConcePTIONAlgorithmPregnancies#29]
the numbers of Termination appear to be too high. After checking the D3_Stream_CONCEPTSET, we found that the ICPC code W82 - abortion spontaneous is used to define "Interruption" which mainly contribute to the count of termination. This should not be correct. 

Could you tell us how the Unknown is defined? we can find quite a few diganose code.

**Comment by GiorgioLimoncella** [comment]
Hi Jing,
a pregnancy is defined as UNK only when there is no record related to the end of the pregnancy (e.g. only an ongoing record is retrieved).

Regarding ICPC code W82: this is probably an error, we will notify the codelist creators @cduransalinas @RosaMGini

**Comment by jingzhuio** [comment]
@GiorgioLimoncella  
Hi Giorgio,
Hope all is well! I'm  just wondering if there's any updates with the codelist/scripts since last time. :)
Best, Jing
