### ISSUE TITLE
Error in script 

### ISSUE THREAD

**Issue by emilyholthuispharmo** [ARS-toscana/ConcePTIONAlgorithmPregnancies#30]
@clobart @GiorgioLimoncella  Hi both!

I was just running the script however, I received an error when running this step:
### > source(paste0(thisdir,"/p_parameters_pregnancy/05_check_coding_system.R"))
Error in eval(ei, envir) : 
  There is an error in coding system: one or more coding system in your data are not included in the list of coding systems supported by this script.Please contact the script programmer.

Do you know how I can solve this? 

Many thanks in advance 

Kind regards, Emily

**Comment by clobart** [comment]
Hi Emily, you can skip this message.
Anyway we removed it from the script, because it can be misleading.
Thanks!
