### ISSUE TITLE
Question about opening output in R 

### ISSUE THREAD

**Issue by emilyholthuispharmo** [ARS-toscana/ConcePTIONAlgorithmPregnancies#31]
@GiorgioLimoncella @clobart  

Hi both, hope you are doing well.
I have two short questions regarding opening the output in R.

Firstly, if I want to open the 'HTML_pregnancy_description.html' file, I receive a note that the file is too large to open in the source editor. The file is 14.1 MB and maximal file size is 5 MB. How would you recommend me to open this?

Secondly, I wanted to open the 'D3_pregnancy_final.RData' but when I do so, I receive the warning:
'R graphics engine version 15 is not supported by this version of RStudio. The Plots tab will be disabled until a newer version of RStudio is installed.'. 
Since I dont have the latest update of R according to this warning, is there another way of opening this file?

Many thanks for your help.
With kind regards, Emily

**Comment by karinswart** [comment]
@GiorgioLimoncella @clobart 
Could you please include me in the communication, as Emily soon will be leaving PHARMO?
Thanks, Karin
