### ISSUE TITLE
Error Pandoc conversion

### ISSUE THREAD

**Issue by karinswart** [ARS-toscana/ConcePTIONAlgorithmPregnancies#34]
@clobart @GiorgioLimoncella 
Error: pandoc document conversion failed with error 61

Hi Claudia and Giorgio,
I got this error while running the script. It doesn't produce HTML files. Do you know how we could solve this?
Thanks,
Karin

**Comment by GiorgioLimoncella** [comment]
Hi @karinswart, 

this error seems to be related to folder permissions or something similar, is the programme running on a server?
Could you tell me what is your version of R and what packages are installed? you can find it by writing in the r console sessionInfo()
 
unfortunately it is not an algorithm error and i cannot reproduce it on my machine, but we can make an initial attempt by starting R as administrator and trying rerunning it.  Let me know if it works! 

thanks, Giorgio
