### ISSUE TITLE
Warning in step_03_03_T2.2_internal_consistency_for_itemsets.R

### ISSUE THREAD

**Issue by bpoblador** [ARS-toscana/ConcePTIONAlgorithmPregnancies#39]
@clobart

Runnin the file step_03_03_T2.2 I obtain the next warning: _In max(num spell) : no finite argument to max; returning -Inf_

It is just a warning but i don't know if it's relevant for execution.

**Comment by clobart** [comment]
Thanks for warn us! @bpoblador 

Is the script still running? 
I think we can check the consistency of the results at the end of the run, let us know!

**Comment by bpoblador** [comment]
Yes, it finished normally.
