### ISSUE TITLE
type_of_id is returning all observations as visit_occurence_id

### ISSUE THREAD

**Issue by eimirh** [ARS-toscana/ConcePTIONAlgorithmPregnancies#42]
Hi guys,

@jingzh95 @GiorgioLimoncella 
In the smaller output dataset, the variable type_of_id is returning all values as visit_occurence_id and none as survey_id.
My lovely colleague Jing wrote this for me to describe it better to you guys.
Thanks a lot, Eimir

D3_survey_and_visit_ids$type_of_id[D3_survey_and_visit_ids$meaning_of_id="birth_registry_mother"] <- "SURVEY_id"

**Comment by GiorgioLimoncella** [comment]
Hi, 
we quickly checked and this could happen if the records have both survey_ID and visit_occurrence_ID (but this is not possible, right?). Could you please check if in the dataset D3_groups_of_pregnancies_reconciled (in the g_intermediate folder) there are records with both survey_ID and visit_occurrence_ID? 

with the data.table library the code would be: 

`D3_groups_of_pregnancies_reconciled[!is.na(survey_id) & !is.na(visit_occurrence_id), .N]`

it should return 0!

Thanks, Giorgio

**Comment by jingzh95** [comment]
returns 262552

**Comment by GiorgioLimoncella** [comment]
Hi @jingzh95, 
could you please check in D3_groups_of_pregnancies_reconciled what value the visit_occurrence_ids take when the meaning is "birth_registry_mother"? 
they should all be NA, but they are not

thanks! Giorgio

**Comment by eimirh** [comment]
Hi Giorgio,


It returns the survey_id from the birth registry  (I believe) but names everything visit_occurrence_id.


Ill be back in the data in 30 mins so can check then and confirm.


E



Eimir Hurley, PhD
Researcher

(My name is Irish and is pronounced Ee-mer)

Pharmacoepidemiology and Drug Safety Research Group,
Department of Pharmacy,
Faculty of Mathematics and Natural Sciences,
University of Oslo,
Norway
________________________________

**Comment by jingzh95** [comment]
It's empty string ""

**Comment by GiorgioLimoncella** [comment]
that explains the error!

I changed line 151 of step 'step_05_02_create_D3_final.R'

this is the old code

```
D3_survey_and_visit_ids <- D3_survey_and_visit_ids[!is.na(visit_occurrence_id) , 
                                                   type_of_id := "visit_occurrence_id"]
```

and this is the new one 

```
D3_survey_and_visit_ids <- D3_survey_and_visit_ids[!is.na(visit_occurrence_id) &
                                                     visit_occurrence_id != "" , 
                                                   type_of_id := "visit_occurrence_id"]
```

you can directly change these lines of code in the step, or you can download the entire step (it is already updated on the repo).
once the step has been updated you can run just that. If the R environment has been reset you should first run the first lines in the to_run.R files: 


```

rm(list=ls(all.names=TRUE))

#set the directory where the file is saved as the working directory
if (!require("rstudioapi")) install.packages("rstudioapi")
thisdir<-setwd(dirname(rstudioapi::getSourceEditorContext()$path))
thisdir<-setwd(dirname(rstudioapi::getSourceEditorContext()$path))
setwd(thisdir)

###################################################################
##############        SET INPUT DIRECTORY     #####################
###################################################################

#@ use this below if you want to set different INPUT DIRECTORY
dirinput <- c(paste0(thisdir,"/i_input/")) # remember to use / instead of \



#load parameters
source(paste0(thisdir,"/p_parameters/01_parameters_program.R"))
source(paste0(thisdir,"/p_parameters/02_parameters_CDM.R"))
source(paste0(thisdir,"/p_parameters/03_subpopulations_restricting_meanings.R"))
source(paste0(thisdir,"/p_parameters/04_algorithms.R"))

#load parameters pregnancy
source(paste0(thisdir,"/p_parameters_pregnancy/00_parameters_pregnancy.R"))
source(paste0(thisdir,"/p_parameters_pregnancy/01_prompts.R"))
source(paste0(thisdir,"/p_parameters_pregnancy/02_itemsets.R"))
source(paste0(thisdir,"/p_parameters_pregnancy/03_concept_sets.R"))
source(paste0(thisdir,"/p_parameters_pregnancy/04_algorithms_pregnancy.R"))
source(paste0(thisdir,"/p_parameters_pregnancy/05_check_coding_system.R"))
```

do not hesitate to contact us if you have any doubts!

**Comment by clobart** [comment]
@jingzh95 @eimirh ARS email has not worked since this morning, if you need us, please write here!

**Comment by jingzh95** [comment]
@GiorgioLimoncella Thanks Giorgio! We have updated the script. @eimirh

**Comment by eimirh** [comment]
Thanks a million all for this,

E
