### ISSUE TITLE
No need to check MO tables for VAC4EU

### ISSUE THREAD

**Issue by jingzh95** [ARS-toscana/ConcePTIONAlgorithmPregnancies#45]
@GiorgioLimoncella 
Hi Giorgio,
I can see after EVENTS table, the script analyses MO tables. We have only pregnancy related BMI and smoking extracted from the birth registry for MO tables, which I don't think needs checking. What do you think? Do you want to tell me to comment some lines away? I also add a few meanings from our data to HOSP and PC. Best, Jing

**Comment by GiorgioLimoncella** [comment]
hi @jingzh95,
the script analyses the MO table by default, searching for diagnosis codes. I think we can leave it like that for transparency, it is a standard that is applied to all DAPs (even if it will find nothing).

Regarding the added meanings:  could you explain further? I'm not sure I understand!

Many thanks! Giorgio

**Comment by jingzh95** [comment]
Hi @GiorgioLimoncella 
in p_parameters/04_algorithms, I added a few "meaings_of_this_study" that are in our dataset but not listed in the script. For example "hospitalisation_not_overnight_primary" for "HOSP" or "primary_care_main_diagnosis" for "PC". 
-Jing

**Comment by jingzh95** [comment]
@GiorgioLimoncella 
For the MO tables, I asked only because it has been taking quite a while to run. For this report we have more data than last time and everything takes so long to run. I have been seeking help for reducing the amount of time it takes for each step. Best, Jing

**Comment by GiorgioLimoncella** [comment]
@jingzh95  thank you very much for your work! 
I will also add these meaning in the repository here in GitHub

Giorgio

**Comment by jingzh95** [comment]
> @jingzh95 thank you very much for your work! I will also add these meaning in the repository here in GitHub
> 
> Giorgio
Ignore me if you already knew! All DAPs are required to add values of vocabulary type to here: https://docs.google.com/spreadsheets/u/0/d/1vPZwzQyjXlmmE1vvx3r1Jkw3Juz2DLjU9dKgEo8MijE/htmlview#gid=1562369704
These might save some time for type things in.;)
Best, Jing
