### ISSUE TITLE
CONCEPTSETS start from 2018 regardless the year in INSTANCE

### ISSUE THREAD

**Issue by jingzh95** [ARS-toscana/ConcePTIONAlgorithmPregnancies#47]
Morning @GiorgioLimoncella !
Just want to double check with you: In INSTANCE table, for hospitalisation (NPR for EVENTS) and birth registry data (MBRN for SO) we put 20100101 in "since_when_data_complete"; for primary care (KUHR for EVENTS) we in 20180101 for that (see the screenshot right below). If PROMPT is from birth registry and CONCEPTSETS is from EVENTS (diagostic code), then the CONCEPTSETS only start from 20180101 (see the screenshot after). Is that what it's meant to be?
![image](https://user-images.githubusercontent.com/48298514/201866928-8c0e7fc5-bfca-4630-942a-c73b34004193.png)

![image](https://user-images.githubusercontent.com/48298514/201867732-8ce96505-da49-483a-b188-fc9df39ec269.png)

Best, Jing

**Comment by GiorgioLimoncella** [comment]
Hi @jingzh95, 

can you please check two html files? they would be:

-  g_describe_HTML/02/D3_STREAM_CONCEPTSETS

-  g_describe_HTML/03/D3_STREAM_CONCEPTSETS_CHECK

these files describe all records retrieved from conceptsets before the internal consistency checks (D3_STREAM_CONCEPTSETS) and after (D3_STREAM_CONCEPTSETS_CHECK). 
In the 'origin' section of these files, you can see where the records come from, if there is a problem in the dates of the INSTANCE table, you will find the distribution of "origins" different in the two files.

if NPR is not present among the origins, the events table and its codes should be checked! 

In addition, the values in this graph seem strange to me, do they seem plausible compared to the results of the other instances? 

Best, Giorgio

**Comment by jingzh95** [comment]
Hi @Giorgio
![image](https://user-images.githubusercontent.com/48298514/201924421-eeab518f-91a8-400e-80e6-973d63ad14fa.png)
Limoncella 
Thanks for the thorough instructions! NPR (and DAR-cause of death registry) is included in CONCEPTSETS but not in CONCEPTSETS_CHECK.   The bar graph from CONCEPTSETS below makes sense to me in a way that "primary_care_main_diangosis" has the longest bar.:) Angela is giving a more thorough checking and we shall let you know if anything!
![image](https://user-images.githubusercontent.com/48298514/201923980-3c37de85-17d6-441b-ab87-f0432ac93496.png)
Here is the scrshot of CONCEPTSETS_CHECK:
![image](https://user-images.githubusercontent.com/48298514/201925302-f71e5d3e-fe50-4b25-90d0-fe84a6edc062.png)
Best, Jing

**Comment by GiorgioLimoncella** [comment]
it seems that the origin table names are different in INSTANCE and EVENT, this could be the reason why NPR records do not pass the checks. 
In INSTANCE you have "NPR" and in EVENT instead you have "NPR.BUP", "NPR.PVH", .... .

If so, could you harmonise the names of the origin and try running againg?
many thanks! Giorgio

**Comment by GiorgioLimoncella** [comment]
@jingzh95  I am closing the issue (I think it is solved), in case there are other problems you can tag me and I will reopen it!
