### ISSUE TITLE
Add new visit_meaning for EpiChron

### ISSUE THREAD

**Issue by bpoblador** [ARS-toscana/ConcePTIONAlgorithmPregnancies#48]
Dear @GiorgioLimoncella and @clobart ,

For the newest instance of Pfizer project we have extraceted all control prengancy visits. Due to that, we need to include the meaning "pregnancy_control_visit" withing the meanings to take into account for the algorithm, together with the "first_pregnancy_visit" already included.

Or if you think that is better to put for all of them the same meaning, we can do it also.

**Comment by clobart** [comment]
Dear @bpoblador,

Yes, it's perfect to add this in the meaning of visits, but we need to check the imputation.
Can we can consider "pregnancy_control_visit" as an ongoing pregnancy?
If yes, it will have the imputation for start and end of pregnancy as the ongoing.

Let us know how we can proceed, and thanks!!

**Comment by bpoblador** [comment]
Yes, the pregnancy control visits implies the pregnancy is ongoing. Then we will have 2 meanings for pregnancy visits: first_pregnancy_visit and pregnancy_control_visit

**Comment by GiorgioLimoncella** [comment]
Dear @bpoblador,

we have added the new meaning in _01_prompts_EpiChron.R_  and updated the other steps involved.
You can download this new version from the branch **version_3.1**.

**Comment by bpoblador** [comment]
Done! Thanks
