### ISSUE TITLE
Preg_Algo_3.1 error messages

### ISSUE THREAD

**Issue by jingzhuio** [ARS-toscana/ConcePTIONAlgorithmPregnancies#49]
![image](https://user-images.githubusercontent.com/106582967/208083117-a259fc5e-6b86-4c11-9b37-7a8f60017669.png)
![image](https://user-images.githubusercontent.com/106582967/208083181-f46922d0-942b-45fa-98b8-d0e96b2fdf4f.png)
![image](https://user-images.githubusercontent.com/106582967/208083241-5e73d37f-e55a-44f2-876c-c7efbe63c4c8.png)
![image](https://user-images.githubusercontent.com/106582967/208083313-533f30a8-1330-44db-919e-a5c4de19524f.png)
@GiorgioLimoncella @clobart 
Hi Giorgio and Claudia,
We have run the new pregnancy algorithm last night and here are the screenshots of the error messages. The R session is till open if you want to have a look soon-ish. 

Best, Jing

**Comment by LAMaglan** [comment]
Just to follow-up, the error in the first screenshot happens in 
https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/blob/version_3.1/p_steps_pregnancy/step_01_03_T2.1_create_conceptset_datasets.R

And what is strange is that we do not have "MEDICAL_OBSERVATIONS_AP", but that was never a problem before in previous versions?

**Comment by GiorgioLimoncella** [comment]
Hi @LAMaglan and @jingzhuio, 

sorry for the late reply!

- regarding the first error: is it possible that you ran the script on simulated data before?  (MEDICAL_OBSERVATIONS_AP is in i_input) if so, could you try deleting all folders starting with g_ (or move them out of the algorithm directory) and run it again using the input directory of your instance? 

- regarding the second error: we have made some minor changes to the 'internal_consistency' steps, could you try to re-download the version 3.1 and run it again? (or just  replace _step_03_01_T2.2_internal_consistency_for_prompts.R_ and _step_03_02_T2.2_internal_consistency_for_conceptsets.R_)


the other errors seem a consequence of the the previous ones

Many thanks, 
Giorgio

**Comment by jingzhuio** [comment]
Hi @GiorgioLimoncella 
We did run on the simulated data by accident because for some reason the srcipt don't pick up the right dirinput correctly. It happend with 3.0 as well. We write the dirbase and dirinput by hand.
I have now deleted all the g_ folders, updated those two scripts and started a rerun. Shall let you know how it goes. @LAMaglan

**Comment by jingzhuio** [comment]
![image](https://user-images.githubusercontent.com/106582967/208905150-8310a79d-1e96-4305-9ff7-9e14e82fd0f5.png)
Hi @GiorgioLimoncella
The scripts finshed and produced results. I'm aware that the codelist is updated and it might be involving definition of Termination. Here is the screenshots of the results of Termination from 3.0 and 3.1. They look pretty much the same. Is this what you expected? 
Best, Jing
