### ISSUE TITLE
Prompts seems don't be used

### ISSUE THREAD

**Issue by bpoblador** [ARS-toscana/ConcePTIONAlgorithmPregnancies#50]
Dear @GiorgioLimoncella and @clobart 

After run the algorithm, the results show that only conceptset data has been used, but we have also prompts. Do you know why this happend?

![image](https://user-images.githubusercontent.com/99145664/209131720-3eaf7af1-dfe0-48db-93b1-e40d8bcbd7ad.png)

Bea

**Comment by GiorgioLimoncella** [comment]
Hi @bpoblador,
this is very strange! 
Did this happen after entering the new meaning of visits?
Has something changed in the INSTANCE table?

could you please check the file **D3_Stream_PROMPTS.html** in the folder _g_describe_HTML/02_ and **D3_Stream_PROMPTS_check.html** in the folder _g_describe_HTML/03_?
these files provide you with a description of the records from the PROMPTs before and after the consistency checks 

Giorgio

**Comment by bpoblador** [comment]
Hi @GiorgioLimoncella , 

Yes, this happend after the modifications the other times I have run this algorithm the prompts has been included.  

D3_Stream_PROMPTS.html doesn't exist in the folder g_describe_HTML/02 and neither does D3_Stream_PROMPTS_check.html in the folder g_describe_HTML/03. 

![image](https://user-images.githubusercontent.com/99145664/209310156-289bbe3a-01d1-4017-8467-107073dfd906.png)

In both folders appear the files regarding conceptsets and itemsets, but the last one doesn't appear in the graph.

Bea

**Comment by GiorgioLimoncella** [comment]
@bpoblador could you please check if also **SURVEY_ID_BR.html** is missing? (in g_describe_HTML/01_01)

many thanks!

**Comment by bpoblador** [comment]
@GiorgioLimoncella  It is not missing, it is there:
![image](https://user-images.githubusercontent.com/99145664/209336448-6871bbcc-fe3a-4b40-b980-fe80c91c0669.png)

**Comment by GiorgioLimoncella** [comment]
@bpoblador 

if you open it you should find a description of how many records were detected from the _survei_id_, could you please check and tell me if the numbers seem correct to you? (approximately)  

if the numbers look correct the problem should be in _step_02_01_T2.2_create_pregnancies_from_prompts.R_, I'm checking it now!

**Comment by bpoblador** [comment]
Yes, the numbers seem correct. We are going to check if any error is produced when we run the file step_02_01_T2.2_create_pregnancies_from_prompts.R,

**Comment by asanmej** [comment]
After checking and running **step_02_01_T2.2_create_pregnancies_from_prompts.R**, it looks like the issue for catching the promt are in the merge of line 42, adding to the merge the parameter **allow.cartesian = T** seems to solve the problem. Now, it creates  D3_Stream_PROMPTS.html in in the folder g_describe_HTML/02. Most of the data shown in the html look like fine, but there are some parts with a lot of missing data in the report. I am still checking if everything is solved

**Comment by GiorgioLimoncella** [comment]
Hi @asanmej, @bpoblador,  

this is strange. The merge is done using the survey_id as the key and there seems to be a lot of repeated survey_ids. If you want we can arrange a call and check the problem together!

**Comment by bpoblador** [comment]
Hi @GiorgioLimoncella, if you have availability this week we can meet and see what is happening. I'm sending our avaliability by email.

**Comment by bpoblador** [comment]
You were right, we had duplicated records. Once fixed it runs without errors. 

Thanks!
