### ISSUE TITLE
SIDIAP - Version 3.1 - Step "step_07_01_create_aggregated_tables.R"

### ISSUE THREAD

**Issue by carloalbertobis** [ARS-toscana/ConcePTIONAlgorithmPregnancies#52]
![image](https://user-images.githubusercontent.com/7137238/209641730-1012ffcf-02d0-4eda-9f24-79e6ddc6ed4a.png)

D3_pregnancy_reconviled_valid : In the age_at_start_of_pregnancy column we have some NA values (9 rows).
In these cases meaning_end_date takes the value of primary_care_pregnancies_abortion.
But not every case of primary_care_pregnancies_abortion are NA in age_at_start_of_pregnancy,

**Comment by GiorgioLimoncella** [comment]
_step_02_01_T2.2_create_pregnancies_from_prompts.R_ has been updated and the bug is fixed,

thanks @carloalbertobis!

**Comment by LAMaglan** [comment]
We at UOSL are facing the same problems (see screenshot), even after downloading the latest version of the scripts.
![step_07_01_create_aggregated_tables_error](https://user-images.githubusercontent.com/29206211/210330444-f47bc0e8-eae9-4330-a2f1-ddee9dbd2ffb.png)


This prevents almost all  tables in `step_07_01_create_aggregated_tables.R` from being made (see screenshot of last
csv-files that are created),
![missing_csv_files](https://user-images.githubusercontent.com/29206211/210330232-15237511-c21d-428b-946e-36e2ab473afe.png)


which I think also get used in the HTML report? (see screenshot)
![missing_tables_HTML](https://user-images.githubusercontent.com/29206211/210330213-af77cdc8-fec4-4365-a0a3-51200b88c8e1.png)

**Comment by GiorgioLimoncella** [comment]
Hi @LAMaglan, 

it seems that in the dataset **D3_pregnancy_reconciled_valid** (in the g_intermediate folder) there are missing pregnancy start dates. Could you tell me what values the "meaning_end_date" column takes on the rows where "pregnancy_start_date" is NA? 

I would do this with the data.table package: 

`table(D3_pregnancy_reconciled_valid[is.na(pregnancy_start_date), meaning_end_date])`

Many thanks!

**Comment by LAMaglan** [comment]
It is different for the three projects that UOSL/Norway are participating in (CONSIGN, ConcePTION, VAC4EU):

![CONSIGN_D3_meaning_end_date](https://user-images.githubusercontent.com/29206211/210334400-8e035bfa-5aa4-4419-830b-03eee31ac19b.png)
CONSIGN  = birth_registry_child

![VAC4EU_D3_meaning_end_date](https://user-images.githubusercontent.com/29206211/210334467-8f1f8f4f-b86c-4d53-a46a-bfe15f73a962.png)
VAC4EU = birth_registry_mother

Still running the pregnancy scripts for ConcePTION. Do you want me to also check when finished?

**Comment by GiorgioLimoncella** [comment]
no thanks no need! seems to be all from the prompts, can you tell me what is the type of end of pregnancy? 

`table(D3_pregnancy_reconciled_valid[is.na(pregnancy_start_date), type_of_pregnancy_end])`

thanks!

**Comment by LAMaglan** [comment]
For VAC4EU and CONSIGN, 
`table(D3_pregnancy_reconciled_valid[is.na(pregnancy_start_date), type_of_pregnancy_end])`
gives "UNK" (see example screenshot)
![VAC4EU_D3_type_of_pregnancy_end](https://user-images.githubusercontent.com/29206211/210344177-2e4c3c4a-8415-4aef-ab99-bf2fc37a287a.png)

**Comment by GiorgioLimoncella** [comment]
I added this line in the file _step_02_01_T2.2_create_pregnancies_from_prompts.R_ (in p_step_pregnancy folder) at row 403:

   ```
 dataset_pregnancies3<-dataset_pregnancies3[!is.na(pregnancy_end_date) & is.na(pregnancy_start_date) & type_of_pregnancy_end=="UNK",
                                               `:=`(pregnancy_start_date = pregnancy_end_date - 280, 
                                                    imputed_start_of_pregnancy = 1, 
                                                    meaning_start_date=paste0("imputed_itemset_from_",type_of_pregnancy_end))]
```

you can add them in your local machine (or download the step from GH) and run the script again, this should solve the problem. 

if you want to save time you can skip these lines of the _to_run_:

```
# 01 RETRIEVE RECORDS FRM CDM
system.time(source(paste0(thisdir,"/p_steps/step_01_1_T2.1_create_spells.R")))
system.time(source(paste0(thisdir,"/p_steps/step_01_2_T2.1_create_dates_in_PERSONS.R")))
system.time(source(paste0(thisdir,"/p_steps/step_01_3_T2.2_population_description.R")))  

# 01 RETRIEVE RECORDS FRM CDM FOR PREGNANCY
system.time(source(paste0(thisdir,"/p_steps_pregnancy/step_01_01_T2.1_create_prompt_datasets.R")))
system.time(source(paste0(thisdir,"/p_steps_pregnancy/step_01_02_T2.1_create_itemsets_datasets.R")))
system.time(source(paste0(thisdir,"/p_steps_pregnancy/step_01_03_T2.1_create_conceptset_datasets.R")))
```

**Comment by LAMaglan** [comment]
Great! That seems to have fixed the problem. You can close this issue.

**Comment by GiorgioLimoncella** [comment]
excellent! thanks @LAMaglan
