### ISSUE TITLE
Uneeded setting of path "dirproducts" 

### ISSUE THREAD

**Issue by LAMaglan** [ARS-toscana/ConcePTIONAlgorithmPregnancies#53]
Current line 19 of `01_parameters_program.R` can be deleted
https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/blob/version_3.1/p_parameters/01_parameters_program.R
`dirproducts <- paste0(thisdir,"/i_input/")`
does not seem to be used, but probably better to remove to avoid confusion, since `i_input` is test/development data?

**Comment by GiorgioLimoncella** [comment]
Yes, you are right! I commented that line.

thanks @LAMaglan
