### ISSUE TITLE
duplicated pregnancy from primary care?

### ISSUE THREAD

**Issue by jingzhuio** [ARS-toscana/ConcePTIONAlgorithmPregnancies#54]
![image](https://user-images.githubusercontent.com/106582967/210765699-07ab3896-fd70-4fec-910c-02ff028bb53c.png)
Hi @GiorgioLimoncella @clobart,
We have rerun the up-to-dated pregnancy algorithm and have 3 small issue/questions:
1. As you can see the total counts of pregnancy went up from 2017-2020. Around 55,000 per year should be the correct number. After checking the INSTANCE table, we suspect that the extra pregnancies during that period are from primary care and secondary care specialist which are from KUHR;
2. Could you tell us how to understand the "order_quality"? For example for Live Birth (screenshot below), there are pink and blue pop up during the same period where potential duplicated pregnancies are counted. 
![image](https://user-images.githubusercontent.com/106582967/210766718-a23fe737-56a5-43dc-9309-abc1083b5e09.png)
We could read ourselves if you have any documents that explain OR we could have quick call, preferably soon because analytical scripts need to use the D3_pregnancy_final and we have deadline on 19th of Jan. from Moderna for finishing the analytical script.
3. What doest the x-axis mean in the Ongoing and why it's a perfect square? 
![image](https://user-images.githubusercontent.com/106582967/210767577-bc941358-b82e-42d3-ae99-bae9c1161c50.png)
@LAMaglan

**Comment by GiorgioLimoncella** [comment]
Hi @jingzhuio, 

this is the correct definition of the quality:


- **1**  EUROCAT: both pregnancy_start_date and pregnancy_end_date are recorded

- **2**  PROMPT: both pregnancy_start_date and pregnancy_end_date are recorded
 
- **3**	ITEMSETS: both pregnancy_start_date and pregnancy_end_date are recorded

- **4**	CONCEPSETS: pregnancy completed and pregnancy_start_date recorded
 
- **5**	PROMPT: pregnancy completed and pregnancy_start_date not available and imputed
 
- **6**	ITEMSETS: pregnancy completed and pregnancy_start_date not available and imputed

- **7**	CONCEPSETS: pre-term birth, meaning non primary care,  pregnancy_start_date not available and imputed

- **7**	CONCEPSETS: at-term birth, meaning non primary care,  pregnancy_start_date not available and imputed

- **7** CONCEPSETS: post-term birth, meaning non primary care,  pregnancy_start_date not available and imputed

- **8**	CONCEPSETS: live birth, meaning non primary care, pregnancy_start_date not available and imputed 

- **9**	CONCEPSETS: still birth, meaning non primary care,  pregnancy_start_date not available and imputed
 
- **10**  CONCEPSETS: interruption, meaning non primary care,  pregnancy_start_date not available and imputed
 
- **11**  CONCEPTSETS: spontaneous abortion, meaning non primary care, pregnancy_start_date not available and imputed
 
- **12**  CONCEPTSETS: ectopic pregnancy, meaning non primary care, pregnancy_start_date not available and imputed
 
- **13**  CONCEPSETS: still birth possible, meaning non primary care,  pregnancy_start_date not available and imputed

- **14**  CONCEPSETS: interruption possible, meaning non primary care,  pregnancy_start_date not available and imputed

- **15**  CONCEPSETS: spontaneous abortion possible, meaning non primary care,  pregnancy_start_date not available and imputed

- **20**  CONCEPTSETS: meaning implying primary care, pregnancy_start_date not available and imputed, end date estimated with record date 
 
- **25**  all Streams: ongoing pregnancy and pregnancy_start_date recorded
 
- **50**  all Streams: ongoing pregnancy having pregnancy_start_date not available and imputed 


(I saw that in the htlm file there is an error in the description, I will correct it)



It does seem that the pregnancies are duplicated, I would suggest to arrange a call and see the issue together. 

In the meantime could you confirm that the pregnancies from the survey_id are not all imputed to the same date? (e.g. 1st July) 

and could you also check that the person_ids are linkable between survey_id and PC records (and between KUHR and MBRN)?


regarding the ongoing graph: you are right the graph is misleading, in this case it means that all the ongoing pregnancies are in 2021 (more than 60,000)


Many thanks!

**Comment by jingzhuio** [comment]
Many thanks @GiorgioLimoncella !!!
Would Wednesday morning any time between 10-12 work for you? Our colleague for ConcePTION Vera would like to join as well. Feel free to send me an invitation to jing.zhao@farmasi.uio.no for the following slots:
Wednesday 10-12 (preferably), 14-15.30;
Thursday 9-11 (preferably).
Speak to you soon!

**Comment by clobart** [comment]
bug in 04_algorithm for ICPC fix

**Comment by jingzhuio** [comment]
Hi @GiorgioLimoncella 
we (vac4eu) ran the latest version over the weekend and noticed that the results reflect the issue we had before with KUHR. Apart from that, other years seems to have more pregnancies than expected:
![image](https://user-images.githubusercontent.com/106582967/224798193-c46e0741-833f-4218-8201-03d5684cf20f.png)

Was there any changes in the merging steps? Practically, would you suggest us to use previous version for the upcoming result and filter KUHR out?
