### ISSUE TITLE
Error in step_02_03_T2

### ISSUE THREAD

**Issue by karinswart** [ARS-toscana/ConcePTIONAlgorithmPregnancies#56]
Hi @GiorgioLimoncella,
I have the following error in step_02_03_T2:

Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'S:/DataPrive/SAS-Projecten/VAC4EU/PfizerCovVAC/Data Characterisation/ConcePTIONAlgorithmPregnancies-version_4.0/g_intermediate/LastMestrualPeriodImplyingPregnancy.RData', probable reason 'No such file or directory'

Can you help with this?
Thanks!

**Comment by GiorgioLimoncella** [comment]
Hi @karinswart, 

I found the error, you can download the fixed version of the script from the repository (not the release), by clicking on the green button "code", as in the image. 


![Screenshot 2023-04-28 alle 14 39 03](https://user-images.githubusercontent.com/78428400/235150127-1be97e89-fcd1-477e-b573-da677d6d3161.png)

**Comment by karinswart** [comment]
Thanks, @GiorgioLimoncella!
Should I rerun all? Or just the parameters and continue where I was?

**Comment by GiorgioLimoncella** [comment]
It would be better to relaunch everything!

**Comment by karinswart** [comment]
Ok, will do!

**Comment by karinswart** [comment]
Hi @GiorgioLimoncella,
Another issue in step_04_01_T2:
Error in .checkTypos(e, names_x) :
Object 'pregnancy_with_dates_out_of_range' not found amongst CONCEPTSETS, EUROCAT, PROMPT, ITEMSETS

Could you again assist with this ? Thank you!

**Comment by GiorgioLimoncella** [comment]
Hi @karinswart, 

It seems that the variable "pregnancy_with_dates_out_of_range" was not created. 

This variable is constructed in internal consistency checks, basically checking that the date of the pregnancy record is included in the data reliability period. 

The data reliability period is retrieved from the INSTANCE table. 

Could you please check that the variabial "source_table_name" in the INSTANCE.csv file takes the same value as the origin variables in the others tables?  (e.g. mo_origin in MEDICAL_OBSERVATION, origin_of_event in EVENT, so_origin in SUVEY_OBS, ...)
