### ISSUE TITLE
Error in step_04_01_T2.2 - FISABIO

### ISSUE THREAD

**Issue by elisacm98** [ARS-toscana/ConcePTIONAlgorithmPregnancies#57]
Hi @GiorgioLimoncella,

We had the following error running the pregnancy script:

![image](https://user-images.githubusercontent.com/102016400/235650050-34fdd130-b51d-48ef-85a6-dabb54bbe942.png)

Can you help us to solve it? 

Thanks!

**Comment by GiorgioLimoncella** [comment]
Hi @elisacm98, 

It seems that the variable "pregnancy_with_dates_out_of_range" was not created.

This variable is constructed in internal consistency checks, basically checking that the date of the pregnancy record is included in the data reliability period.

The data reliability period is retrieved from the INSTANCE table.

Could you please check that the variabial "source_table_name" in the INSTANCE.csv file takes the same value as the origin variables in the others tables? (e.g. mo_origin in MEDICAL_OBSERVATION, origin_of_event in EVENT, so_origin in SUVEY_OBS, ...)

These variables should match the name of the original table before ETL.

**Comment by elisacm98** [comment]
Hi @GiorgioLimoncella,

Thanks for your help. As you said there was an error in some of the "origin variables". We run again the script, and now we had an error  in step_01_03_T2.1:
<img width="336" alt="image" src="https://user-images.githubusercontent.com/102016400/235869016-3d7db816-8830-4a39-83c0-382251d65620.png">
The error was produced while creating the PROCEDURES conceptsets. 

Can you help us again? Thanks!

**Comment by GiorgioLimoncella** [comment]
Hi @elisacm98, 

unfortunately I can't figure out the problem, there might be some issue with the original tables, if you agree I will contact you by email to arrange a call to check them together.

**Comment by elisacm98** [comment]
Hello again @GiorgioLimoncella, @OlgaPaoletti and @DavideMessinaARS, 

We ran the step again without ths strange procedure code and now it worked.

Thanks for your help!

**Comment by elisacm98** [comment]
Hello again, 

We had another issue while running the pregnancy script. This time it was in step_05_01_T2.3, and it seems that the problem is that we don't have an identification for the born child. We saw in the script that some other values are created empty if they are missing, however this is not the case for child_id. Creating an empty record would be a solution to our problem or is this variable important for the next steps of the script? At the moment and in the near future, we are not going to have this variable. So if it´s important we would need to discuss how to implement the script without it.

 I attach a screenshot of the error: 

 
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/102016400/236410029-0558ceed-5f71-4eea-8711-4a1c9a75299b.png)

I include my colleague @urchuegu, so she can participate. 

Thanks a lot for your help!

**Comment by GiorgioLimoncella** [comment]
Hi @elisacm98, 

the child_id is not mandatory, you are right it should have been created empty like the other variables. I corrected the step by adding the line you suggested, you can download it from GH and replace. 

In addition, could you replace also step 5_03 as well? we made some minor changes, you can find that updated in GH as well!

links:

- https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/blob/version_4.0/p_steps_pregnancy/step_05_01_T2.3_merge_stream_of_same_person.R

- https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/blob/version_4.0/p_steps_pregnancy/step_05_03_predictive_model.R

Thanks!

**Comment by elisacm98** [comment]
Hi @GiorgioLimoncella,

Thanks for the updated steps. We have run the script and now it has worked.

Thank you very much for your help during the process!
