### ISSUE TITLE
error in source(paste0(thisdir,"/p_steps_pregnancy/step_05_03_predictive_model.R"))

### ISSUE THREAD

**Issue by frasansa** [ARS-toscana/ConcePTIONAlgorithmPregnancies#58]
Dear @GiorgioLimoncella,

We are running the Github development version of the algorithm (updated at 2023/05/16), as we have seen that there are some updates in the predictive model than in the release version.

We have found an error in source(paste0(thisdir,"/p_steps_pregnancy/step_05_03_predictive_model.R"))

`Error in rbindlist(l, use.names, fill, idcol) :
  Item 2 has 45 columns, inconsistent with item 1 which has 42 columns. To fill missing columns use fill=TRUE.`

The error is produced in line 1005:

 ```
 D3_pregnancy_reconciled_before_excl <- rbind(D3_pregnancy_reconciled_before_excl, DT_ov_pregnancy) 
(and also in line 1006 :  D3_groups_of_pregnancies_reconciled_before_excl <- rbind(D3_groups_of_pregnancies_reconciled_before_excl, DT_ov)
```

It can be fixed using the arguments:  "use.names = TRUE, fill = TRUE" but I'm not sure if the dfs should have the same number of columns.

Let me know what do you think,

Thank you,
Francisco.

**Comment by GiorgioLimoncella** [comment]
Hi @frasansa, 

I think adding  "use.names = TRUE, fill = TRUE"  is the right solution, quickly checking I saw that we created some additional columns just for VID (to define the hierarchy inside the prompts) and that might be the problem. 

I updated the step in the repository with this correction, let me know if it works.
Thank you very much!

Giorgio

**Comment by frasansa** [comment]
Yes, @GiorgioLimoncella. With this fix the script works fine.
Thanks for your quick response.
Have a nice day,
Francisco.
