### ISSUE TITLE
p_steps_pregnancy_step_05_03_predictive_model step running for long period of time or throws error

### ISSUE THREAD

**Issue by alexcoldea** [ARS-toscana/ConcePTIONAlgorithmPregnancies#59]
The step is running well until the "Random forest section" but it's taking very long to run the predict(RF, DT_red_yellow_model) function. We left it for approx. 12 hours but it still wouldn't pass this section after several attempts.

After R failed with a fatal error it was able to pass this section failing with an error:
Error: Column 3 passed to [f]order is type 'list', not yet supported.
DT_ov<-DT_ov[order(pers_group_id, hyerarchy, order_quality, -sd, record_date), ]
- I tried re-running the script after this error but it's halting again around the predict function.

Thank you for your help.
Best, Alex

**Comment by GiorgioLimoncella** [comment]
Hello Alex, 

I think something went wrong in the creation of the previous dataset. 
The step should not take much time!

Can we have a call to check the problem together? in case I will contact you by email to arrange it.

Best, Giorgio

**Comment by alexcoldea** [comment]
@GiorgioLimoncella Thank you. Yes, that would be great. 

Best, Alex
