### ISSUE TITLE
UOSL: no "D3_mother_child_ids.RData" output

### ISSUE THREAD

**Issue by LAMaglan** [ARS-toscana/ConcePTIONAlgorithmPregnancies#62]
I see in a recent commit that this was added to https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/blob/version_4.2.1/p_parameters_pregnancy/01_prompts/01_prompts_UOSL.R
```r
meaning_of_relationship_child[["UOSL"]] <- list("gestational_mother")
```
If this is based on values from the PERSON_RELATIONSHIPS table (meaning_of_relationship),
then it should be "birth_mother", not "gestational_mother". In PERSON_RELATIONSHIPS, we only have "birth_mother" and "undefined_parent"

**Comment by OlgaPaoletti** [comment]
We set this meaning based on your ETL document but if it is not correct please change the meaning to "birth_mother" and rerun. This should solve the problem.
If the problem is solved and you see the output table in the g_output, then you can download the new DP2 release from:  https://github.com/IMI-ConcePTION/DP2_SSRI-SNRI/releases/tag/DP2_v1.0

**Comment by LAMaglan** [comment]
I will have to check with the colleagues in UOSL who wrote the ETL document and performed the ETL.
So I relay the information properly,  is it correct that :
```r
meaning_of_relationship_child[["UOSL"]] <- list(<input value here>)
```
is based on the relevant value from "meaning_of_relationship" in `PERSON_RELATIONSHIPS`?

**Comment by OlgaPaoletti** [comment]
You have to fill in the list with the meaning identifying the mother in the PERSON_RELATIONSHIPS table. In some DAPs the meaning is "gestational_mother" in others is "birth_mother". You should check in your istance which one of the 2 is in your case

**Comment by LAMaglan** [comment]
@GiorgioLimoncella 
New problem: it turns out that the set of scripts posted here
https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/releases/tag/release_4.2.1
did not actually include the change to UOSL (adding `meaning_of_relationship_child` to https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/blob/version_4.2.1/p_parameters_pregnancy/01_prompts/01_prompts_UOSL.R
)
After downloading from the "main" page https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies , this change is included. Now, I have changed it from "gestational_mother" to "birth_mother" (after talking with those in UOSL that have created the CDM tables)
However, when running this, I get the error that the object `meaning_of_relationship_child` does not exist (see screenshot).
![01_prompts_error_new](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/assets/29206211/5a9fc12b-be3f-4d87-ae92-7222166dd741)
