### ISSUE TITLE
order_quality NA for birth registry

### ISSUE THREAD

**Issue by jingzhuio** [ARS-toscana/ConcePTIONAlgorithmPregnancies#67]
Hi Giorgio,
We are running on the 10k sample of our new data extraction. I updated the parameters in `p_parameters_pregnancy/02_itemsets/02_itemsets_UOSL`:

```
svlen_dg -> SVLEN_DG 
fdato_xxx -> FDATO_DIFFERANSEDAGER
dodkat -> DODKAT
```

In `D3_pregnancy_final`, all the origins NPR, KUHR and MBRN appear but for some reason the quality of `PROMPT` are all grey `NA`. Due to the restricted ETL rules,  we didn't compute the "`start_of_pregnancy`" in SO table as it's not really the "`so_source_column`" with "`so_source_value`". Could this be the cause?
![image](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/assets/106582967/f7a97b99-9565-4379-a06c-39a6b8ec0b2e)

**Comment by jingzhuio** [comment]
Hi @GiorgioLimoncella again
I will be on holiday during week 37-39. In case you have some time to help us look at this in the near future, please contact Luigi and Anteneh (@LAMaglan @antepharma).

**Comment by GiorgioLimoncella** [comment]
Hi @jingzhuio, 

please let me know if this problem has occurred again with the latest version. 

See you soon!
Giorgio
