### ISSUE TITLE
p_parameters_pregnancy/02_itemsets/02_itemsets_UOSL.R

### ISSUE THREAD

**Issue by jingzhuio** [ARS-toscana/ConcePTIONAlgorithmPregnancies#69]
Hi Giorgio,
This time we received data with different reference date for every 320 individuals. For this reason and the fact that Moderna will have a subanalysis for pregancy outcomes, we created two SO tables:

- one for children (so_meaning == "birth_registry_child") with so_date derived from chidren's difference days of delivery, and
- one for mother  (so_meaning == "birth_registry_child") with so_date derived from mother's difference days of delivery.

I didn't keep the mother's difference days of delivery in so_source_value. I wonder if I should and how to change the settings "FDATO_..." in this file.

from previouls extractions we have:
![image](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/assets/106582967/84aec391-fbbf-4696-a54b-cd6eeaba1a57)
![image](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/assets/106582967/ebefda7b-b1cf-41ac-b8cc-f93a706a1673)
![image](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/assets/106582967/cb84108e-f965-4bf7-b177-e89123694950)

@LAMaglan @antepharma

**Comment by GiorgioLimoncella** [comment]
Hi @jingzhuio,

sorry for the late reply, I had not noticed the issue. 
I think the issue has been resolved. If you still have problems we can make another call! 
I am closing the issue 

Giorgio
