### ISSUE TITLE
UOSL (ConcePTION): "meaning_of_survey_pregnancy_this_datasource" not found

### ISSUE THREAD

**Issue by LAMaglan** [ARS-toscana/ConcePTIONAlgorithmPregnancies#70]
@GiorgioLimoncella 
For the UOSL ConcepTION data, we get an error the "`meaning_of_survey_pregnancy_this_datasource` was not found"
in step_01_01_T2.1_create_prompt_dataset.R (see screenshot)

![step_011_01_T2-1_error](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/assets/29206211/e8396e4f-e62a-423d-866c-7539650cd67e)

Is there something that I should fill out?

The script is currently running the following steps after (despite the error)

**Comment by GiorgioLimoncella** [comment]
Hi @LAMaglan, 

did you notice some errors before? 

In the file 01_prompt_UOSL.R there seems to be a line missing, you could add this to line 17 and try again:

`meaning_of_relationship_child <- vector(mode="list")`

I recommend you stop the script and re-run because step step_01_01_T2.1_create_prompt_dataset.R is crucial

**Comment by LAMaglan** [comment]
Hi @GiorgioLimoncella 
You are right, there was another error I did not spot (I run everything, and R does not stop despite error for these scripts).

Problem running 01_prompts.R 
![prompts_error](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/assets/29206211/e894220d-f61c-40b3-a8db-15040c8e7865)

"Error in length(meaning_of_survey_pregnancy_child) : object 'meaning_of_survey_pregnancy_child' not found"

**Comment by GiorgioLimoncella** [comment]
Sorry for the inconvenience, could you also add this two lines in file 01_prompt_UOSL.R:

```
meaning_of_survey_pregnancy_child <- vector(mode="list")
meaning_of_survey_pregnancy_child[["UOSL"]] <- NA
```

so in total you should try add these 3 lines:

```
meaning_of_relationship_child <- vector(mode="list")
meaning_of_survey_pregnancy_child <- vector(mode="list")
meaning_of_survey_pregnancy_child[["UOSL"]] <- NA
```

many thanks

**Comment by LAMaglan** [comment]
Another error:

![ARS_pregnancy](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/assets/29206211/5e4b17cc-751c-4db6-b976-2495a642d8ab)

I guess either `meaning_of_survey_pregnancy` is incorrect, or do something like

`meaning_of_survey_pregnancy <- vector(mode="list")` 
?

**Comment by GiorgioLimoncella** [comment]
that should be the code:

```
meaning_of_survey_pregnancy <- vector(mode="list")

meaning_of_survey_pregnancy[["UOSL"]][["livebirth_or_stillbirth"]]<-list("birth_registry_mother")
meaning_of_survey_pregnancy[["UOSL"]][["ongoing_pregnancy"]]<-list()
meaning_of_survey_pregnancy[["UOSL"]][["spontaneous_abortion"]]<-list()
meaning_of_survey_pregnancy[["UOSL"]][["induced_termination"]]<-list()
meaning_of_survey_pregnancy[["UOSL"]][["other"]]<-list()

meaning_of_relationship_child <- vector(mode="list")
meaning_of_relationship_child[["UOSL"]] <- list("gestational_mother")

meaning_of_survey_pregnancy_child <- vector(mode="list")
meaning_of_survey_pregnancy_child[["UOSL"]] <- NA

```

**Comment by LAMaglan** [comment]
Great, that seems to have solved this issue. You can close it
