### ISSUE TITLE
Error step_07_02 "pregnancies_description" (version 5.0.1)

### ISSUE THREAD

**Issue by LAMaglan** [ARS-toscana/ConcePTIONAlgorithmPregnancies#72]
@GiorgioLimoncella  There is an error when running step_07_02 (see screenshot) for us at UOSL.
![error_step_07_02_pregnancies_description](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/assets/29206211/b9c5f104-ef30-4e40-b29d-9ea9206e2cab)

Note: the main HTML-file `HTML_pregnancy_description.html` is created (I guess this is the second part?)

**Comment by GiorgioLimoncella** [comment]
Hi @LAMaglan,

There seems to be an error in the calculation of the average gestational age at the first record for LOSTFU. The error occurs only when restricting the analysis to the years 2015-2019.

I cannot understand the error this way, I suggest commenting out lines 670-687 of the file "p_macro/pregnancies_description_HTML.Rmd" and complete the execution. 

From the results we can understand what produces this error.

**Comment by LAMaglan** [comment]
![update](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/assets/29206211/6c1bd173-5af7-443f-9492-f95ceb50e8d5)
The rmarkdown script ran with the lines commented out. Is there something else you want me to show you / run?

**Comment by LAMaglan** [comment]
Follow-up: this only occurs for the UOSL ConcePTION dataset, not the (new) VAC4EU dataset

**Comment by GiorgioLimoncella** [comment]
Hi @LAMaglan , 

Many thanks!

I await your news on the analysis of the results.

I will send you instructions shortly explaining how to upload the results to DRE, but unfortunately I will have to ask you to run an added step which is to copy some metadata into the g_export_manuscript folder before the upload.This step will not affect the results in any way.

**Comment by LAMaglan** [comment]
We get this error again for  v5.1.0. I did what you suggested before and it fixed it.
> I cannot understand the error this way, I suggest commenting out lines 670-687 of the file "p_macro/pregnancies_description_HTML.Rmd" and complete the execution.

Again, this only happens for the ConcePTION data at UOSL, not VAC4EU.
I'm not sure this is a "permanent" soltuion.
Tagging @verarumi for future reference, in case something needs to be changed with the CDM tables

**Comment by GiorgioLimoncella** [comment]
Thank you @LAMaglan , 
The error in question does not affect the results, so it is OK to comment it as you did at the time.
