### ISSUE TITLE
g_describe_HTML

### ISSUE THREAD

**Issue by erarasfisabio** [ARS-toscana/ConcePTIONAlgorithmPregnancies#74]
Dear @GiorgioLimoncella 
The script has finished. I have checked the g_describe_HTML, and all the folders are empty except 01_01; which contains: Person_rel_PROMPT_dataset.html and  @SURVEY_ID_BR.html. I could not find any HTML related to the pregnancy description. 
I look forward to hearing from you.
 #Laia

**Comment by GiorgioLimoncella** [comment]
Hi @erarasfisabio, 

did any errors appear during the run? 
If the file was not generated, the script probably did not reach the end. 

We can arrange a short call to check together.

**Comment by erarasfisabio** [comment]
Dear @GiorgioLimoncella ,
To meet today, I will be available 9 to 15:30 (except 11 to 12:30)

I could find the errors below: 
1) Error in eval(parse(text = paste0(study_var, "_", df2))) :
object 'GESTAGE_FROM_DAPS_CRITERIA_WEEKS_SURVEY_OBSERVATIONS_META' not found

2) Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
3) Error in .checkTypos(e, names_x) :
Object 'pregnancy_with_dates_out_of_range' not found amongst CONCEPTSETS, EUROCAT, PROMPT, ITEMSETS
4) Error in eval(jsub, SDenv, parent.frame()) :
5) Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection **(Repeated several times)

Laia

**Comment by erarasfisabio** [comment]
this is already solved.
thank you
