### ISSUE TITLE
SIDIAP: DescribeThisDataset function

### ISSUE THREAD

**Issue by carloalbertobis** [ARS-toscana/ConcePTIONAlgorithmPregnancies#75]
In step_01_01_T2.1_create_prompt_datasets.R

![image](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/assets/7137238/1c022216-13a1-43ac-9e2f-e947f6bc2d70)

I get this problem in that line.
I have commented it so that I skip it (for now).
Commenting on that part I was able to finish the step.

![image](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/assets/7137238/c0fc970a-b92e-45d4-8348-7da23334d7e5)

But the problem always occurs when using the DescribeThisDataset function, for example in the following step step_01_02_T2.1_create_itemsets_datasets.R I get the same error

@GiorgioLimoncella

**Comment by GiorgioLimoncella** [comment]
Hi @carloalbertobis, 
Unfortunately, I can't figure out what's causing the error, can we arrange a call and check together? 
In case I email you, 
Giorgio

**Comment by carloalbertobis** [comment]
I answered you by e-mail
