### ISSUE TITLE
run_post_verification_script

### ISSUE THREAD

**Issue by erarasfisabio** [ARS-toscana/ConcePTIONAlgorithmPregnancies#76]
Hi @GiorgioLimoncella, 
We have already completed the verification csv and run the verification script, but the download of the packages has failed. How can we solve it?
____________________________________________________________________________________
The downloaded source packages are in
	'D:\Users\53378158B\AppData\Local\Temp\RtmpewNmyF\downloaded_packages'
Quitting from lines 22-45 (Report_verification_preg.Rmd) 
Error: package or namespace load failed for 'multipanelfigure' in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called 'magick'
____________________________________________________________________________________
We look forward to hearing from you.
Thank you, 
Laia

**Comment by GiorgioLimoncella** [comment]
As agreed, I will send you the link for a call via email.
Giorgio
