### ISSUE TITLE
missing library in to_run_post_verification_script

### ISSUE THREAD

**Issue by LAMaglan** [ARS-toscana/ConcePTIONAlgorithmPregnancies#77]
I get the error that function `fct_inorder` cannot be found when running the "to_run_post_verification.Rmd" script 
(see screenshot)
![error_report_verification_preg](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/assets/29206211/18f32d91-302f-4e54-b6ec-8919f78f1499)

When I explicitly load the package `forcats`, it works.
Suggestion: add a line that loads `forcats` in the "to_run_post_verification.Rmd" script

**Comment by GiorgioLimoncella** [comment]
Thanks @LAMaglan,
I will modify the file as you suggested
