### ISSUE TITLE
SIDIAP step 7_02

### ISSUE THREAD

**Issue by carloalbertobis** [ARS-toscana/ConcePTIONAlgorithmPregnancies#78]
D3_mother_child_ids.Rdata

![image](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/assets/7137238/2b0f6395-0625-4839-9dbc-b05c68feecb5)

![image](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/assets/7137238/a4e54aa4-96e8-4260-8752-27c1244f5003)

![image (1)](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/assets/7137238/361c23f6-1d82-42b1-beb1-0bd2b67d7907)

@GiorgioLimoncella

**Comment by GiorgioLimoncella** [comment]
Hi @carloalbertobis, 
You are right that an 'if' is missing in step '**step_07_02_pregnancies_description**.R'. I corrected it this way: 

**OLD**
```
print("Creating HTML files for descriptions ")

#loading the datasets
load(paste0(dirtemp,"D3_pregnancy_reconciled_valid.RData"))
load(paste0(dirtemp,"D3_groups_of_pregnancies_reconciled.RData"))
load(paste0(diroutput,"D3_mother_child_ids.RData"))


```


**NEW**

```
print("Creating HTML files for descriptions ")

#loading the datasets
load(paste0(dirtemp,"D3_pregnancy_reconciled_valid.RData"))
load(paste0(dirtemp,"D3_groups_of_pregnancies_reconciled.RData"))
if(this_datasource_has_person_rel_table){
  load(paste0(diroutput,"D3_mother_child_ids.RData"))
}else{
  D3_mother_child_ids <- data.table()
}

```


thank you very much for debugging!
