### ISSUE TITLE
Error step 05_05

### ISSUE THREAD

**Issue by anallg** [ARS-toscana/ConcePTIONAlgorithmPregnancies#79]
@GiorgioLimoncella
> system.time(source(paste0(thisdir,"/p_steps_pregnancy/step_05_05_create_D3_final.R")))
Error in fwrite(D3_pregnancy_reconciled, paste0(dirvalidation, "/D3_pregnancy_reconciled.csv")) : 
  object 'D3_pregnancy_reconciled' not found
Timing stopped at: 161.3 23.55 166.8

As the error message states, that file doesn`t exists in that directory and I think there are no previous errors.

**Comment by GiorgioLimoncella** [comment]
Hi @anallg, 
I can't understand what the problem is. I will email you, I would like to schedule a call if possible.
Giorgio
