### ISSUE TITLE
V5.1.4.1: UOSL_Error "thisdatasource_has_prescriptions" not found

### ISSUE THREAD

**Issue by jingzhuio** [ARS-toscana/ConcePTIONAlgorithmPregnancies#81]
Hi @GiorgioLimoncella 
we are  running v5.1.4.1 go this error message from`02_parameters_CDM.R`
@antepharma

**Comment by GiorgioLimoncella** [comment]
Hi @jingzhuio, 

the parameter **thisdatasource_has_prescriptions** is created in the step _/p_parameters/01_parameters_program.R_.
Can you please run this step again and double-check that no errors are present? 

Many thank, 
Giorgio

**Comment by jingzh95** [comment]
> Hi @jingzhuio,
> 
> the parameter **thisdatasource_has_prescriptions** is created in the step _/p_parameters/01_parameters_program.R_. Can you please run this step again and double-check that no errors are present?
> 
> Many thank, Giorgio

Hi Giorgio, this step works fine. The last line in the console says "This datasource is OSLO"

**Comment by GiorgioLimoncella** [comment]
The problem is that the name of the data source in the CDM_SOURCE table was changed.
The parameters were set with _UOSL_ as the name of the data source. Has only the name been changed or is the ETL also different?

**Comment by jingzh95** [comment]
Hi Giorgio, it is the same. I think the different parts for ConcePTION data and VAC4EU data I have already changed. 
I tried to continue and it worked now.  Feel free to close the issue.
I'm terribly sorry for the issue. I cannot explain why.

**Comment by GiorgioLimoncella** [comment]
Do not worry at all! 
Let me know if there are any other problems
