### ISSUE TITLE
Aarhus(DANREG) : Error in step_04_02_T2.2_create_flowchart.R

### ISSUE THREAD

**Issue by kimimia** [ARS-toscana/ConcePTIONAlgorithmPregnancies#82]
We got this error below:
Error in dcast.data.table(D3_all_stream_person_id, person_id ~ criteria, 
  can not cast an empty data.table
In addition: Warning message:
In min(exclusion) : no non-missing arguments to min; return Inf

I can see that table D3_all_stream is not empty, but D3_all_stream_person_id/_single_criteria/tmp are empty. 

Please let me know if you need further information from us to solve this issue.

**Comment by GiorgioLimoncella** [comment]
This step tries to create a flowchart for the years 2015-2019 and 2019-2021. Is it possible that there is no data between 2019 and 2021?

**Comment by kimimia** [comment]
The data in our birht-registry start from 01JAN2021.

**Comment by GiorgioLimoncella** [comment]
@kimimia @GiorgioLimoncella

**Comment by GiorgioLimoncella** [comment]
Hi @kimimia, 

The error should be fixed in version 5.2.1. You can find the release at this link: 

https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/releases
