### ISSUE TITLE
SIDIAP: Error in step 01_03

### ISSUE THREAD

**Issue by DanOV** [ARS-toscana/ConcePTIONAlgorithmPregnancies#85]
Hi,

We found an error in step_01_03_T2.1_create_conceptset_datasets.R
During this step, the server crashes as it uses all the RAM available.

Tried to run the script step by step and this is happening during the first part in CreateConceptSetDatasets()

Thanks,

**Comment by GiorgioLimoncella** [comment]
Hi @DanOV, 

I have published release 5.2, which updated some steps to optimize RAM usage (also _step_01_03_T2.1_create_conceptset_datasets.R_). 

You can download from this page: 

https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/releases

Let me know if the error is solved with this version!
